### ISSUE TITLE
Spatial Cluster Size Error

### ISSUE THREAD

**Issue by meaksu** [edward130603/BayesSpace#101]
Hi,
I apologize for all the error questions but I am on the last step of doing joint clustering for a very large dataset of 90 samples. When running the SpatialCluster function I get this error.

`> sce.combined <- spatialCluster(sce.combined, use.dimred = "HARMONY", q = 7, platform = "Visium")
Neighbors were identified for 251657 out of 251704 spots.
Fitting model...
Error in cluster.FUN(Y = as.matrix(Y), df_j = df_j, nrep = nrep, n = n,  : 
  Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD`

Is there anywhere I can enable that parameter or would it have to be done in the source code? Or is sce.combined simply too large to use? Thanks!

**Comment by edward130603** [comment]
Sorry I missed this earlier. Yes it would need to be done in the source code. As a workaround, I think you can try fewer iterations and it might work.
