### ISSUE TITLE
SpatialCluster() using SCTransform array

### ISSUE THREAD

**Issue by jeji0209** [edward130603/BayesSpace#103]
Hello, thank you for creating this excellent tool. 
I have a Seurat object, which I have integrated using the SCTransform (Pearson residualised) array.
Therefore, now I have an "integrated" array based on the SCTransformed normalization.
I would like to use this array to apply the SpatialCluster() function, by converting my seurat object into a singlecellexperiment object with "SCT" as the mainExpname.
However, because BayesSpace uses lognormalization method for spatial preprocessing, I am not sure if this is an appropriate method.

Is is okay to apply an SCTransformed & integrated assay for spatial clustering? If not, are there any possible suggestions for this process?
Thanks in advance.

**Comment by JessicaChevallier** [comment]
Hello,

I'm also interested in using SCTransform and applying the BayesSpace clustering method. I was wondering if you tried out what you suggested? 

Thank you!

**Comment by edward130603** [comment]
Sorry I was not able to reply to this one earlier. You should be able to use your custom normalization approach. Make sure to set the `logcounts` assay of your SCE as your Pearson-normalized residuals, which shoudl be in a format with cells in columns and genes in rows. Make sure the row/colnames match those of `sce`. Set using `logcounts(sce) = mySCTmatrix`.

Then you can run `spatialPreprocess` using `log.normalize = TRUE`. https://rdrr.io/bioc/BayesSpace/man/spatialPreprocess.html

**Comment by oghzzang** [comment]
> Sorry I was not able to reply to this one earlier. You should be able to use your custom normalization approach. Make sure to set the `logcounts` assay of your SCE as your Pearson-normalized residuals, which shoudl be in a format with cells in columns and genes in rows. Make sure the row/colnames match those of `sce`. Set using `logcounts(sce) = mySCTmatrix`.
> 
> Then you can run `spatialPreprocess` using `log.normalize = TRUE`. https://rdrr.io/bioc/BayesSpace/man/spatialPreprocess.html

Dear Edward, 
Is it correct with `log.normalize = TRUE`?

I think we need to define the option to `log.normalize = FALSE` to use the `data` slot of `SCT` assay.

**Comment by edward130603** [comment]
yes you are correct, should be FALSE for that argument
