### ISSUE TITLE
About the input file of BayesSpace

### ISSUE THREAD

**Issue by makabakayu** [edward130603/BayesSpace#112]
Hi,
I wondered if I could apply this method to non-gene expression matrix, where my input is a low-dimensional matrix with columns representing spots while rows representing the proportions of each cell type, and there are only 30 rows so I don't need to perform pre-processing and PCA. 
I initially used the option to skip pca, but in the next step qTune() I reported an error:
```
Error in value[[3L]](cond) : 
  invalid subscript 'type' in 'reducedDim(<SingleCellExperiment>, type="character", ...)':
  'PCA' not in 'reducedDimNames(<SingleCellExperiment>)'
```
it seems that it has to use the results of pca, so I perform the pca, but again I got an error when running the `sce <- qTune(sce, qs=seq(2, 10), platform="Visium")`:
```
Neighbors were identified for 41055 out of 41067 spots.
Error in `[<-`(`*tmp*`, g, modelName, value = bic(modelName = modelName,  : 
  subscript out of bounds
```
And I just can't figure it out 
Is there any way for the method to take my matrix directly as input without any processing?

Thanks!

**Comment by edward130603** [comment]
You can first set your expression matrix using something like this:

```r
reducedDim(sce, "mySlotNameHere") = myMatrixHere
```

I think this matrix should be in the format with spots in rows and cell type proportion in column.

Then you can run `qTune` or `spatialCluster` using the argument `use.dimred = "mySlotNameHere"` (see documentation here: https://rdrr.io/bioc/BayesSpace/man/spatialCluster.html)

**Comment by makabakayu** [comment]
It works! Thank you for your prompt answer!
