### ISSUE TITLE
v1.13.0 when skipping spatialPreprocess and specifying a use.dimred : Not compatible with requested type

### ISSUE THREAD

**Issue by berniejmulvey** [edward130603/BayesSpace#124]
Please disregard.

**Comment by berniejmulvey** [comment]
Nope, thought spatialCluster() was running but it did return the same error after all. Please ignore.

**Comment by ez-eirclin** [comment]
glad you were able to find a solution. thanks for using our package and feel free to reach out in the future if you have more questions!

**Comment by edward130603** [comment]
glad you were able to find a solution. thanks for using our package and feel free to reach out in the future if you have more questions!
