### ISSUE TITLE
Interoperability with Seurat

### ISSUE THREAD

**Issue by ximbao** [edward130603/BayesSpace#29]
Hello, my name is Felipe and I'm working with Visium ST data.

I was excited to run BayesSpace and see the results for the enhanced clustering and I was wondering how can I use the results from BayesSpace on Seurat. Specifically, I'm interested in replacing the clusters on Seurat with the ones I find using BayesSpace.

I tried following this vignette: https://satijalab.org/seurat/v3.1/conversion_vignette.html with no luck. 

Any insights would be appreciated!

Thank you very much for your effort with this amazing tool!

Best, 

Felipe

**Comment by edward130603** [comment]
Hi Felipe, we recommend creating a new Seurat Object from the information in the SingleCellExperiment.

>`seurat <- Seurat::CreateSeuratObject(counts=logcounts(sce),
                                       assay='Spatial',
                                       meta.data=as.data.frame(colData(sce)))
  seurat <- Seurat::SetIdent(seurat, value = "spatial.cluster")`

This code chunk is taken from [one of our examples online](https://edward130603.github.io/BayesSpace/articles/ji_SCC.html), where we use Seurat for DE analysis following BayesSpace clustering/enhancement. In the SCE, the BayesSpace cluster assignments are stored in `colData` under the name `spatial.cluster`. Hope this helps!

Edward

**Comment by ximbao** [comment]
Perfect, thank you!
