### ISSUE TITLE
Cluster characteristics

### ISSUE THREAD

**Issue by chsher** [edward130603/BayesSpace#30]
Thank you for creating this great tool. I am new to R and your tool is very user-friendly. I followed your vignette and have constructed my clusters and subspots - is there a way that I can obtain the characteristics of each cluster, e.g., what is the cell type composition and what are the differentially expressed genes?

**Comment by edward130603** [comment]
We have a a [tutorial ](https://edward130603.github.io/BayesSpace/articles/ji_SCC.html)on our website that include a differential expression analysis.

For cell type annotation, you can either do it manually based on the DE genes or use an annotation tool like [SingleR](https://bioconductor.org/packages/devel/bioc/vignettes/SingleR/inst/doc/SingleR.html). SingleR can annotate at the cluster level if you input your vector of cluster identities that you get from BayesSpace into the clusters parameter of the `SingleR()` function (i.e. `clusters = myClusteredSce$spatial.cluster`). You will also need to choose a suitable reference cell type dataset. SingleR has some built-in ones and we have found that the [blueprint_encode](https://rdrr.io/github/dviraran/SingleR/man/blueprint_encode.html) reference works well for human PBMCs.

If this doesn't work well, there are some other approaches you can try such as Seurat's label transfer method and various spatial deconvolution methods, though all will need you to have a reference dataset.

**Comment by chsher** [comment]
Many thanks for pointing me to these resources!

**Comment by chsher** [comment]
Thank you very much for sharing your DE tutorial. I tried running it but unfortunately encountered an error message from the seurat_cluster_DE function: 
```
Error in seurat@assays$Spatial@data %>% as.matrix %>% t %>% scale %>%  : 
  could not find function "%>%"
```

**Comment by edward130603** [comment]
You will need to load the dplyr library before running the code.

Best,
Edward
