### ISSUE TITLE
Error: package or namespace load failed for ‘BayesSpace’

### ISSUE THREAD

**Issue by alberto-valdeolivas** [edward130603/BayesSpace#32]
Hello,

First of all, congratulations for your **BayesSpaces** recent publication and for developing this nice package.

I installed the package from Bioconductor and then from your github repo. In both cases, I am having an issue when loading the package: 

```
library(BayesSpace)
Error: package or namespace load failed for ‘BayesSpace’:
 object ‘colBlockApply’ is not exported by 'namespace:beachmat'
```

Do you have any idea about this issue? Which version of the  **beachmat** package is loaded in your example vignettes?

Many thanks and best regards,
Alberto.

**Comment by alberto-valdeolivas** [comment]
I am closing this issue because I managed to install and load BayesSpace locally, so I guess that it is a problem with my HPC cluster.

**Comment by edward130603** [comment]
Hi Alberto, thanks for giving our package a try. In case you do want to run BayesSpace on your HPC cluster later, you will probably need to see if you can update your R and/or Bioconductor versions. 

BayesSpace does not directly use beachmat, but it is a indirect dependency through some other packages. We've tested that BayesSpace installs and loads in R versions 4.0-4.1, bioc versions 3.12-3.13, and beachmat v2.4-2.8.
