### ISSUE TITLE
Vignette data download does not work

### ISSUE THREAD

**Issue by crichgriffin** [edward130603/BayesSpace#33]
Hi, 

I was trying to run through your vignette, but the following command 
`melanoma <- getRDS(dataset="2018_thrane_melanoma", sample="ST_mel1_rep2")`
returned the error `Error: Dataset/sample not available` 

Perhaps the file has moved or been renamed?

Best wishes,
Charlotte

**Comment by edward130603** [comment]
Hi Charlotte, we had to move our data at some point, though the current version of the code on github or on Bioconductor v.3.13 (which requires the newest R version) should both work. 

If you aren't able to update to the newest version, a quick workaround is to run the following:
```
library(BayesSpace)
library(assertthat)
library(RCurl)
getRDS <- function(dataset, sample, cache=TRUE) {

    url <- "https://fh-pi-gottardo-r-eco-public.s3.amazonaws.com/SpatialTranscriptomes/%s/%s.rds"
    url <- sprintf(url, dataset, sample)
    assert_that(url.exists(url), msg="Dataset/sample not available")
    
    if (cache) {
        bfc <- BiocFileCache()
        local.path <- bfcrpath(bfc, url)
    } else {
        local.path <- tempfile(fileext=".rds")
        download.file(url, local.path, quiet=TRUE, mode="wb")
    }
    
    readRDS(local.path)
}
```

This puts the updated version of `getRDS()` into your global environment.
