### ISSUE TITLE
How can I view the initially assigned labels of the spots and spatialPreprocess

### ISSUE THREAD

**Issue by Nuwaisir-1998** [edward130603/BayesSpace#36]
Does running `spatialCluster(..., nrep=1, ...)` give me the initial labeling? Or is it the state of the labels of the spots after 1 iteration? If yes, then how can I get the very first spot label assignments?
I'm trying to see how these assigned labels change with the number of iterations. So, I'm iterating over the number of iterations (nrep) of your spatialCluster method and using clusterPlot to plot the figure. Am I following the right approach?

Thanks.

**Comment by edward130603** [comment]
`nrep=1` gives the initial cluster labels. You can also find these in `sce$cluster.init`. I would recommend saving chains using `save.chain = TRUE` in `spatialCluster()`. Then you can look at your saved chains using `mcmcChain()`. Here is an example:

```r
library(BayesSpace)
melanoma <- getRDS(dataset="2018_thrane_melanoma", sample="ST_mel1_rep2") #load data
melanoma <- spatialPreprocess(melanoma, platform="ST", #preprocess
                              n.PCs=7, n.HVGs=2000, log.normalize=FALSE)
melanoma <- spatialCluster(melanoma, q=4, platform="ST", d=7,
                           nrep= 3000, burn.in=100, #3000 reps
                           save.chain=TRUE) #save chains
#labels are stored in the "z" attribute
chain = mcmcChain(melanoma, "z") #matrix with 3000 rows (reps) by 293 columns (# of spots)
clusterPlot(melanoma, chain[1,]) #plot first iteration
clusterPlot(melanoma, chain[2500,]) #plot 2500th iteration
```

Let me know if you have further questions.
