### ISSUE TITLE
datasets download

### ISSUE THREAD

**Issue by GiovanniCS** [edward130603/BayesSpace#37]
Hi,
thank you for developing this interesting tool! I'm trying to download the datasets cited in your supplementary notes (Dorsolateral prefrontal cortex,Melanoma,Ovarian cancer and Squamous cell carcinoma), but I'm encountering some difficulties.
I know there is the getRDS function to download sce objects, but i haven't found how to configure "dataset" and "sample" parameters anywhere..
Moreover, none of the following calls work on my machine 
`
sce1 = getRDS("2020_maynard_prefrontal-cortex", "151673")
sce2 = getRDS("2020_maynard_prefrontal-cortex", "151674")
sce3 = getRDS("2020_maynard_prefrontal-cortex", "151675")
melanoma <- getRDS(dataset="2018_thrane_melanoma", sample="ST_mel1_rep2")
`
All of them return "Error: Dataset/sample not available". I tried also with wget (like wget https://fh-pi-gottardo-r.s3.amazonaws.com/SpatialTranscriptomes/2018_thrane_melanoma/ST_mel1_rep2.rds) but i get "ERROR 403: Forbidden.".

Is there something I'm missing?
Thank you!

**Comment by edward130603** [comment]
Hi Giovanni, we had to move our data at some point, though the current version of the code on github or on Bioconductor v.3.13 (which requires the newest R version) should both work. 

If you aren't able to update to the newest version, a quick workaround is to run the following:
```
library(BayesSpace)
library(assertthat)
library(RCurl)
getRDS <- function(dataset, sample, cache=TRUE) {

    url <- "https://fh-pi-gottardo-r-eco-public.s3.amazonaws.com/SpatialTranscriptomes/%s/%s.rds"
    url <- sprintf(url, dataset, sample)
    assert_that(url.exists(url), msg="Dataset/sample not available")
    
    if (cache) {
        bfc <- BiocFileCache()
        local.path <- bfcrpath(bfc, url)
    } else {
        local.path <- tempfile(fileext=".rds")
        download.file(url, local.path, quiet=TRUE, mode="wb")
    }
    
    readRDS(local.path)
}
```

This puts the updated version of `getRDS()` into your global environment.

**Comment by GiovanniCS** [comment]
The workaround did the trick! 
Thank you very much!
