### ISSUE TITLE
How to obtain the ground truth labels

### ISSUE THREAD

**Issue by vanhoan310** [edward130603/BayesSpace#38]
Dear developers,

I am interested in running BayesSpace on the ST datasets in the BayesSpace paper. I can download the datasets using the function getRDS(), e.g., melanoma <- getRDS(dataset="2018_thrane_melanoma", sample="ST_mel1_rep2"). Do you know how to obtain the ground truth labels provided by the original papers from the object melanoma?

Thanks!

**Comment by edward130603** [comment]
Hi Van, unfortunately the ST datasets don't precisely align the H&E image with the expression spots so it's hard to directly label spots given that the annotations were only done on the image. We have been comparing our clustering results qualitatively to the annotations for the ST data. The original authors of the paper may be able to help you further: https://cancerres.aacrjournals.org/content/78/20/5970.long
