### ISSUE TITLE
Samples in Figure 2

### ISSUE THREAD

**Issue by suke18** [edward130603/BayesSpace#39]
Hi Edward, 

I read your BayesSpace NBT paper. I am interested in the result in Figure 2 for spatialLIBD data. I wonder which sample shows the highest ARI? Do you use the same clustering setting as the sample 151673 (https://edward130603.github.io/BayesSpace/articles/maynard_DLPFC.html)? 

Best,
Kenong

**Comment by edward130603** [comment]
Hi Kenong, the highest ARI was achieved in sample 151672. For the clustering pipeline, we've streamlined the process a bit since then and haven't gotten around to updating our vignette.  We recommend using `spatialPreprocess()` to perform the log normalization, HVG selection, and PCA. The clustering settings are the same across samples except for the number of clusters, which is determined based on prior knowledge of the number of layers/regions in the sample.

**Comment by suke18** [comment]
Hi Edward, 

For this spatialLIBD data. I found if directly downloading from the `spatilLIBD` package. Some of the samples' layer_guess_reordered information is NA. Did you remove these samples? I downloaded the sample data (151672), and run the pipeline. I got the ARI ~ 0.45. I used 5 clusters and `nrep=5000`. The other settings are the same as the sample (151673). Here are the codes: 

---
dlpfc <- getRDS("2020_maynard_prefrontal-cortex", "151672")
set.seed(101)
dec <- scran::modelGeneVar(dlpfc)
top <- scran::getTopHVGs(dec, n = 2000)
set.seed(102)
dlpfc <- scater::runPCA(dlpfc, subset_row=top)
## Add BayesSpace metadata
dlpfc <- spatialPreprocess(dlpfc, platform="Visium", skip.PCA=TRUE)


q <- 5  # Number of clusters
d <- 15  # Number of PCs
## Run BayesSpace clustering
set.seed(104)
dlpfc <- spatialCluster(dlpfc, q=q, d=d, platform='Visium',
                        nrep=50000, gamma=3, save.chain=TRUE)
## We recoded the cluster labels to match the expected brain layers
labels <- dplyr::recode(dlpfc$spatial.cluster, 3, 4, 5, 6, 2, 7, 1)

## View results
clusterPlot(dlpfc, label=labels, palette=NULL, size=0.05) +
    scale_fill_viridis_d(option = "A", labels = 1:7) +
    labs(title="BayesSpace")


mclust::adjustedRandIndex(dlpfc$spatial.cluster, dlpfc$layer_guess_reordered)
---

Could you figure out the difference from yours? 

Kenong

**Comment by edward130603** [comment]
This is our standard code for preprocessing and clustering now:

```r
library(BayesSpace)
set.seed(100)
sce = getRDS("2020_maynard_prefrontal-cortex", "151672")
q = length(unique(na.omit(sce$layer_guess)))

sce = spatialPreprocess(sce, platform = "Visium")
clust = spatialCluster(sce, q = q)
mclust::adjustedRandIndex(clust$spatial.cluster, sce$layer_guess)
```

I get an ARI of 0.77 here, but results may vary depending on preprocessing steps and seeding. Here I am running 50,000 iterations, which is our default (5,000 is probably a little too low). Hope this helps!

**Comment by suke18** [comment]
Thanks Edward~
