### ISSUE TITLE
qTune error: subscript contains invalid names

### ISSUE THREAD

**Issue by PeifengJi** [edward130603/BayesSpace#40]
Hi:
  First of all, thank you for developing the awesome tool. I am just starting to try out BayesSpace and looks it really useful!
 The data for analysis I am using is converted from Scanpy.
I have transferred the Anndata object to singleCellExperiment object (rds file) using anndata2ri. However, when I analyze the data using BayesSpace with the command:
  sce <- qTune(sce, qs=seq(2, 10), platform='Visium', d=7).
It run error: subscript contains invalid names.
I have tried reconstructing the singleCellExperiment from scratch using:
  sce <- SingleCellExperiment() commands.
But got the exactly the same issue.
I have tried read the data from the out files from space ranger and it works well.
Therefore, could you please figure out how to address the issue. Thank you!

**Comment by edward130603** [comment]
Hi Peifeng, can you check what columns `colData(sce)` contains? If `row` and `col` are not in there, you will need to copy them over to `colData(sce)`.

**Comment by PeifengJi** [comment]
Thanks for your quick reply. This resolved my issue and I got the cells segmented. 
BTW, I have found the difference between the layout of Scanpy and BayesSpace, where the pic is rooted 90. 
For example:
Scanpy plot:
![download](https://user-images.githubusercontent.com/86214818/126098778-581913c2-ba2d-4ebc-8baa-8d5e871203df.png)

In BayesSpace:
<img width="623" alt="截屏2021-07-19 上午11 31 52" src="https://user-images.githubusercontent.com/86214818/126098799-09d40b8d-01b2-4b10-82f0-f8bb5384b8b9.png">

**Comment by edward130603** [comment]
Thanks for trying our tool and glad that you were able to run it on your data! Did you set `row` to the y-axis values and `col` to the x-axis? I'm not super familiar with the AnnData format for spatial experiments so it is possible that you need to do some transformations on the coordinates so that it matches the image orientation.

**Comment by PeifengJi** [comment]
Thank for your response! I will try it!
