### ISSUE TITLE
Running BayesSpace on multiple slides

### ISSUE THREAD

**Issue by smorabit** [edward130603/BayesSpace#42]
Hi,

First of all thank you for such a great tool. The clustering results and spot enhancement are quite remarkable.

I am wondering if it is currently possible to run BayesSpace clustering on multiple slides together? Currently I have 12 slides from similar mouse brain sections (with more being generated by the lab), and I am not sure that it makes sense for me to do a separate BayesSpace clustering for each slide. It seems like [Seurat has a tutorial for clustering multiple slides](https://satijalab.org/seurat/articles/spatial_vignette.html), but their approach does not seem to account for spatial information, only gene expression.

In the last sentence of the discussion for the BayesSpace paper, the authors wrote "it may also be possible to extend BayesSpace to jointly cluster spots from multiple samples given appropriate data normalizations.
online". Is there currently a way to jointly cluster spots from multiple slides using BayesSpace? If not, do you think this feature would come soon, or are you aware of any alternateive approaches?

Cheers,
Sam

**Comment by edward130603** [comment]
Hi Sam, yes we have a vignette describing the multiple sample joint clustering approach, which we will be posting to our website soon. I've attached it here as well. Let me know if you have questions!
[Joint Clustering Analysis.pdf](https://github.com/edward130603/BayesSpace/files/6903515/Joint.Clustering.Analysis.pdf)

**Comment by smorabit** [comment]
Thank you so much, looking forward to trying this out!
