### ISSUE TITLE
getRDS() only offer one example?

### ISSUE THREAD

**Issue by BinDuan** [edward130603/BayesSpace#43]
It is hard to collecte more spatial transcriptome datasets. The function you provide "getRDS" only can get one example, how about other datasets? I wonder if you can provide processed other datasets used in your article and it will be very helpful for other researchers.
Thanks.

**Comment by edward130603** [comment]
The `getRDS()` function should be able to retrieve all the datasets used in our article. The list of datasets is here: https://github.com/msto/spatial-datasets/tree/master/scripts

I've tagged @msto here to see if he has better documentation for the names of datasets and names of samples.

**Comment by BinDuan** [comment]
> The `getRDS()` function should be able to retrieve all the datasets used in our article. The list of datasets is here: https://github.com/msto/spatial-datasets/tree/master/scripts
> 
> I've tagged @msto here to see if he has better documentation for the names of datasets and names of samples.

Thank you so much for your reply. In fact, I had checked the website https://github.com/msto/spatial-datasets/tree/master/scripts carefully before. However, there were only the names of datasets without the names of samples, which are both needed for function getRDS(). I wonder how should I find the names of samples of each datasets. I'll appreciated it if you can help me to solve this. I am looking forward to hearing from you.

Best regards

**Comment by edward130603** [comment]
Here is the list of datasets:

| Dataset  | Sample(s) |
| ------------- | ------------- |
| 2018_thrane_melanoma | ST_mel1_rep2 |
| 2020_maynard_prefrontal-cortex  | 151507, 151508, 151509, 151510, 151669, 151670, 151671, 151672, 151673, 151674, 151675, 151676  |
| 2020_ji_squamous-cell-carcinoma | P4_rep1 |
| 2020_10X-IDC | IDC1 |
| 2020_10X-demo_ovarian-cancer | whole_transcriptome |

**Comment by BinDuan** [comment]
Thank you so much for your help, now it works.
