### ISSUE TITLE
Running BayesSpace clustering on processed Seurat object

### ISSUE THREAD

**Issue by jnmark** [edward130603/BayesSpace#48]
Hi,

Thanks for developing this great tool! I was curious to know if you had any insights or suggestions on the most effective way to run BayesSpace on a fully processed Seurat object containing data from multiple batch corrected samples? Essentially, I would like to add in the clustering from BayesSpace into the Seurat object, so that all other associated metadata, cell deconvolution metrics in the object are maintained and we can really see how much BayesSpace improves those metrics.

Thanks!

**Comment by edward130603** [comment]
Here is some code, hope this helps!

```r
#Load libraries
library(Seurat)
#devtools::install_github('satijalab/seurat-data')
library(SeuratData)
library(BayesSpace)
InstallData("stxBrain")

#Seurat workflow
seurat = LoadData("stxBrain", type = "anterior1") #load seurat data
seurat = Seurat::FindVariableFeatures(seurat) #Simple Seurat workflow for PCs
seurat = Seurat::ScaleData(seurat)
seurat = Seurat::RunPCA(seurat)

#Convert to SCE
diet.seurat = Seurat::DietSeurat(seurat, graphs = "pca") #slim down Seurat obj prior to conversion
sce = as.SingleCellExperiment(diet.seurat) #convert seurat to SCE
colData(sce) = cbind(colData(sce), seurat@images$anterior1@coordinates) #add spatial info to SCE

#BayesSpace Workflow
sce = spatialPreprocess(sce, platform = "Visium", skip.PCA = T, log.normalize = F) #add BayesSpace metadata, without messing with PCA/logcounts
sce = spatialCluster(sce, nrep = 1000, burn.in = 100, q = 10) #quickly cluster via BayesSpace
clusterPlot(sce) #plot via BayesSpace

#Add BayesSpace results to Seurat
seurat@meta.data = cbind(seurat@meta.data, BayesSpace = sce$spatial.cluster) #add BayesSpace clusters to Seurat obj
SpatialDimPlot(seurat, "BayesSpace") #plot via Seurat
```

**Comment by jnmark** [comment]
Hi @edward130603, thanks -- that worked out for me! Just curious - how would this work for the enhanced clustering since that would generate more coordinates; wouldn't there be a mismatch adding it back to the Seurat object?

**Comment by edward130603** [comment]
Hi @jnmark. Yes, for the enhanced clustering you will have to create a new Seurat object from the enhanced SCE. Here is some code copied over from our [vignette](https://edward130603.github.io/BayesSpace/articles/ji_SCC.html), where we used Seurat to do differential expression analysis on enhanced results:

```r
  seurat <- Seurat::CreateSeuratObject(counts=logcounts(sce),
                                       assay='Spatial',
                                       meta.data=as.data.frame(colData(sce)))
  seurat <- Seurat::SetIdent(seurat, value = "spatial.cluster")
```

**Comment by wfma** [comment]
Just wanna say thanks folks for raising this issue! I am just getting my first spatial data and finally be able to run bayesspace (which i have been following for quite some times!)

**Comment by wfma** [comment]
just wanted to see if yall have any plans of making a wrapper for giotto also?

thanks!

**Comment by jzheng25** [comment]
Thank you all for posting the issue as well as responding to it with a wonderful solution! 
I am adapting this now with merged samples (one seurat with multiple ST), and using the PCA obtained from merged and SCTransformed data.

**Comment by ppm1337** [comment]
This solution doesn't work anymore due to the changes made in 7d6997c.

`.find_neighbors` searches for `array_col` and `array_row` instead of `col` and `row`. While it's true that the coordinates in Space Ranger's `tissue_positions.csv` are provided as such, the image coordinates stored in Seurat V3 objects provide `tissue`, `row`, `col`, `imagerow`, `imagecol`. You can check this with `names(seurat@images$anterior1@coordinates)` in your example provided [above](https://github.com/edward130603/BayesSpace/issues/48#issuecomment-908645137) which doesn't work any longer because of `spatialCluster` failing with `Error: subscript contains invalid names`.

Tested with R `4.2.3`, Seurat `4.3.0.1`, SeuratData `0.2.2`, SeuratObject `4.1.3` and BayesSpace `1.11.0`.

**Comment by akhmelevskaya** [comment]
> This solution doesn't work anymore due to the changes made in [7d6997c](https://github.com/edward130603/BayesSpace/commit/7d6997c4e04a6628737b34d8a095650d9ca5bf9e).
> 
> `.find_neighbors` searches for `array_col` and `array_row` instead of `col` and `row`. While it's true that the coordinates in Space Ranger's `tissue_positions.csv` are provided as such, the image coordinates stored in Seurat V3 objects provide `tissue`, `row`, `col`, `imagerow`, `imagecol`. You can check this with `names(seurat@images$anterior1@coordinates)` in your example provided [above](https://github.com/edward130603/BayesSpace/issues/48#issuecomment-908645137) which doesn't work any longer because of `spatialCluster` failing with `Error: subscript contains invalid names`.
> 
> Tested with R `4.2.3`, Seurat `4.3.0.1`, SeuratData `0.2.2`, SeuratObject `4.1.3` and BayesSpace `1.11.0`.

Hi, I have the same error (Error: subscript contains invalid names) running spatialCluster on Seurat preprocessed object, is there a new way to do it?
Or should I run BayesSpace pipeline and Seurat pipeline in parallel and just add BayesSpace clusters to seurat object, or would it be wrong?

**Comment by wsk-byun** [comment]
Just change the column names in the coordinates data.frame.

```r
sce <- as.SingleCellExperiment(seurat)
coords <- seurat@images$slice@coordinates %>%
    dplyr::rename(array_row=row, array_col=col)
colData(sce) <- cbind(colData(sce), coords)
sce <- spatialPreprocess(sce, platform='Visium', skip.PCA=T, log.normalize=F)
````
