### ISSUE TITLE
Do images have to be oriented the same way?

### ISSUE THREAD

**Issue by jdrnevich** [edward130603/BayesSpace#50]
Hello! I am interested in trying BayesSpace on some mouse mid-brain Visium samples. However, the images are not all oriented in the same direction. Will this be a problem when trying to do joint clustering? Your vignette (https://edward130603.github.io/BayesSpace/articles/joint_clustering.html) has the images all in the same orientation. If they do need to be re-oriented to be the same, do you have a function to rotate and/or mirror image? I imaging this needs to be done for the x, y coordinates as well as the actual image itself. Thanks.

**Comment by edward130603** [comment]
Thanks for trying out BayesSpace. The images do not need to be oriented the same way for the joint clustering, although it will be easier for visualization and comparing between samples if they are. To mirror images, you can try multiplying `row` or `col` by -1. Switching `row` and `col` will give you the transpose. Rotating is a bit harder, but it seems there are some packages you can use to do it: https://www.rdocumentation.org/packages/spdep/versions/1.1-8/topics/Rotation or https://rdrr.io/github/ErasmusOIC/SMoLR/man/rotate_coord.html
