### ISSUE TITLE
The issue about getRDS()

### ISSUE THREAD

**Issue by LiYiyan-code** [edward130603/BayesSpace#51]
Hi, recently I used BayesSpace and I found the function getRDS(), and when I run this function, I got this information: "error: Dataset/sample not available". So I found the code of this   [function](https://rdrr.io/bioc/BayesSpace/src/R/utils.R), I want to get the DLPFC data, so I tried to wget this data by using wget https://fh-pi-gottardo-r.s3.amazonaws.com/SpatialTranscriptomes/2020_maynard_prefrontal-cortex/151673.rds,
but I got this formation "2021-09-16 23:50:08 erro 403：Forbidden".
How can I solve my problem?
Thanks for your help!

**Comment by edward130603** [comment]
We had to move our data at some point, though the current version of the code on github or on Bioconductor v.3.13 (which requires the R 4.1) should both work. 

If you aren't able to update to the newest version, a quick workaround is to run the following to update the URL:
```
library(BayesSpace)
library(assertthat)
library(RCurl)
getRDS <- function(dataset, sample, cache=TRUE) {

    url <- "https://fh-pi-gottardo-r-eco-public.s3.amazonaws.com/SpatialTranscriptomes/%s/%s.rds"
    url <- sprintf(url, dataset, sample)
    assert_that(url.exists(url), msg="Dataset/sample not available")
    
    if (cache) {
        bfc <- BiocFileCache()
        local.path <- bfcrpath(bfc, url)
    } else {
        local.path <- tempfile(fileext=".rds")
        download.file(url, local.path, quiet=TRUE, mode="wb")
    }
    
    readRDS(local.path)
}
```

This puts the updated version of `getRDS()` into your global environment.

**Comment by LiYiyan-code** [comment]
Thanks! I have solved id
