### ISSUE TITLE
Is there a way to read in the results of spatialEnhance into Seurat?

### ISSUE THREAD

**Issue by li-shimin** [edward130603/BayesSpace#52]
Hello!

Thank you so much for creating such a useful package. I'm wondering if there's a way to read in the singleCellExperiment object from spatialEnhance into Seurat. Is there a way for the assays to include counts/ logcounts?

Thank you in advance!
Shimin

**Comment by edward130603** [comment]
Hi Shimin. Yes, there are a few steps needed after running spatialEnhance. 

First, the `enhanceFeatures` function can be used to predict subspot level gene expression from principal components. By default, this predicts logcounts. We haven't looked deeply into predicting raw counts, and using the current `enhanceFeatures` function to predict will result in non-integer counts. The enhanced features will be added to the SCE object. 

Afterwards, you can create a new Seurat object from the enhanced SCE. Here is some code copied over from our [vignette](https://edward130603.github.io/BayesSpace/articles/ji_SCC.html), where we used Seurat to do differential expression analysis on enhanced results:

```r
  seurat <- Seurat::CreateSeuratObject(counts=logcounts(sce),
                                       assay='Spatial',
                                       meta.data=as.data.frame(colData(sce)))
  seurat <- Seurat::SetIdent(seurat, value = "spatial.cluster")
```

See also the discussion here: #49
