### ISSUE TITLE
Run FindAllMarkers for enhanced object

### ISSUE THREAD

**Issue by CromitDolores0808** [edward130603/BayesSpace#54]
de_markers <- FindAllMarkers(sce.enhanced)
Error in UseMethod(generic = "Idents", object = object) : 
  no applicable method for 'Idents' applied to an object of class "c('SingleCellExperiment', 'RangedSummarizedExperiment', 'SummarizedExperiment', 'RectangularData', 'Vector', 'Annotated', 'vector_OR_Vector')"

I want to find the marker genes of all cluster in an enhanced object. But the FindAllMarkers didn't work. Thank you.

**Comment by edward130603** [comment]
`FindAllMarkers` is a function that requires a Seurat object as input. You will need to convert the BayesSpace output, which is in SingleCellExperiment format, into Seurat format. We have some example code on how to do this in one of our [vignettes](https://edward130603.github.io/BayesSpace/articles/ji_SCC.html#differential-expression-analysis-1). The linked vignette includes a `seurat_cluster_DE()` function that will convert your (enhanced) sce into Seurat format and then apply `FindAllMarkers()`.  If you have further questions, please reach out again!

**Comment by CromitDolores0808** [comment]
> `FindAllMarkers` is a function that requires a Seurat object as input. You will need to convert the BayesSpace output, which is in SingleCellExperiment format, into Seurat format. We have some example code on how to do this in one of our [vignettes](https://edward130603.github.io/BayesSpace/articles/ji_SCC.html#differential-expression-analysis-1). The linked vignette includes a `seurat_cluster_DE()` function that will convert your (enhanced) sce into Seurat format and then apply `FindAllMarkers()`. If you have further questions, please reach out again!

Many Thanks! It help me a lot.
