### ISSUE TITLE
subset object and re-cluster but lost spatial information

### ISSUE THREAD

**Issue by CromitDolores0808** [edward130603/BayesSpace#55]
Hi! I want to subset the singlecellexperiment object, so I first convert it in to seurat, then using subset function. After subsetting, I want to do spatial cluster for the new subset seurat object, so I convert the seurat object into singlecellexperiment. Finally, re-clustering was working but lost spatial information. Can you help me? Here is my codes: 

sobj <- Seurat::CreateSeuratObject(counts=logcounts(sce.enhanced),
                                   assay='Spatial',
                                   meta.data=as.data.frame(colData(sce.enhanced)))

sobj <- Seurat::SetIdent(sobj, value = "spatial.cluster")

sobj <- subset(sobj, spatial.cluster %in% c("14", "15","18","20"))

sce_converted = sobj %>%
  Seurat::as.SingleCellExperiment()

sce_converted <- spatialPreprocess(sce_converted, platform="ST", n.PCs=7, n.HVGs=2000, log.normalize=FALSE)
sce_converted <- qTune(sce_converted, qs=seq(1, 15), platform="ST", d=7)
qPlot(sce_converted)

sce_converted <- spatialCluster(sce_converted, q=9, platform="ST", d=7,
                      init.method="mclust", model="t", gamma=2,
                      nrep=100000, burn.in=100,
                      save.chain=TRUE)

sce_converted.enhanced <- spatialEnhance(sce_converted, q=9, platform="ST", d=7,
                               model="t", gamma=2,
                               jitter_prior=0.3, jitter_scale=3.5,
                               nrep=10000, burn.in=100,
                               save.chain=TRUE)

clusterPlot(sce_converted.enhanced,label = "spatial.cluster",palette= c(mypal(8),mypal1(8),mypal2(9)),
            platform="Visium")

**Comment by edward130603** [comment]
Can you point out which step(s) have errors and copy over the error msg? I think the problem here is probably related to doing the enhancement on an object that already has subspots. Our `spatialEnhance` function is designed to work on spot-level data. Is your goal here to do a sub-clustering of clusters 14,15,18,20?

**Comment by msto** [comment]
Hi @CromitDolores0808 ,

I don't think you need to convert to Seurat here. Try subsetting the SingleCellExperiment directly, e.g.

```
sce.subset <- sce[, sce$spatial.cluster %in% c(14, 15, 18, 20)]
```

But as Ed points out, the enhancement is intended to be performed on the original spot-level expression.

**Comment by CromitDolores0808** [comment]
> Hi @CromitDolores0808 ,
> 
> I don't think you need to convert to Seurat here. Try subsetting the SingleCellExperiment directly, e.g.
> 
> ```
> sce.subset <- sce[, sce$spatial.cluster %in% c(14, 15, 18, 20)]
> ```
> 
> But as Ed points out, the enhancement is intended to be performed on the original spot-level expression.

Your advice is working. Thanks!

**Comment by CromitDolores0808** [comment]
> Can you point out which step(s) have errors and copy over the error msg? I think the problem here is probably related to doing the enhancement on an object that already has subspots. Our `spatialEnhance` function is designed to work on spot-level data. Is your goal here to do a sub-clustering of clusters 14,15,18,20?

I redo as msto suggested, and It was working. Thank you!
