### ISSUE TITLE
Histopathological annotations of IDC

### ISSUE THREAD

**Issue by wlq762** [edward130603/BayesSpace#57]
Hi, we are now working on the spatial analysis of breast cancer and your IDC tissue section helps us a lot. The problem is that we could not find the histopathological annotations (ground truth) of IDC (Supplementary Figure 11), which is a valuable support for this dataset. I would appreciate if you could share the annotations with us. Thanks!

**Comment by edward130603** [comment]
Apologies for the delay. I've attached the annotations. Let me know if you have further questions
[IDC1_annotations.csv](https://github.com/edward130603/BayesSpace/files/7798571/IDC1_annotations.csv)
!

**Comment by suke18** [comment]
Hello Edward, 

Following up on this IDC dataset, I wonder where to obtain the H&E stained image. The paper mentioned it is from the 10x spatial gene expression datasets. I just want to confirm with you that it is from https://www.10xgenomics.com/resources/datasets/invasive-ductal-carcinoma-stained-with-fluorescent-cd-3-antibody-1-standard-1-2-0. Right? 

Thanks,
KS

**Comment by edward130603** [comment]
yes, that's correct!
