### ISSUE TITLE
`readVisium` fails when feature names include whitespaces

### ISSUE THREAD

**Issue by hisplan** [edward130603/BayesSpace#59]
Hi,

I have a custom zebrafish reference package (FASTA/GTF), and I used this to process a few samples through Space Ranger and Cell Ranger, and I've got the `filtered_feature_bc_matrix` output from Space Ranger. Now, I'm trying to run BayesSpace, but encountered an error:

```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  line 14 did not have 4 elements
Calls: readVisium -> read.table -> scan
Execution halted
```

It turns out that there are some gene names containing a whitespace (in `features.tsv.gz`), and the `read.table` function failed because by default it uses whitespaces as a separator. Since `features.tsv.gz` is a tab-separated file (as the extension `tsv` indicates), I think the `read.table` should be called with `sep=\t` explicitly.

https://github.com/edward130603/BayesSpace/blob/master/R/readVisium.R#L55

**Comment by edward130603** [comment]
Thanks for pointing this out. I've followed your suggestion to update the package and set `sep="\t"`.

**Comment by hisplan** [comment]
Great! Is it possible to install the fix via Bioconductor now? Also, it would be really great if you could create a release in GitHub (versioning) so that users can properly do devops.

Thanks.

**Comment by edward130603** [comment]
The fix is available on the Bioc development version. I'm going to push the changes to the release branch soon so it'll propagate to the Bioconductor release in a few days as well. I've made a GitHub release as well.
