### ISSUE TITLE
error: Mat::row(): index out of bounds

### ISSUE THREAD

**Issue by khomicsk** [edward130603/BayesSpace#60]
Dear all, 

Using a Visium 10x dataset (already analyzed in R), managed to get through normal resolution. 

However, when starting "spatialenhance" I receive the following message:

error: Mat::row(): index out of bounds
Error in iterate_deconv(Y = Y2, df_j = df_j, tdist = tdist, nrep = nrep,  : 
  Mat::row(): index out of bounds

Any suggestion?

Thanks

K

**Comment by edward130603** [comment]
Can you provide the entire function `spatialEnhance()` function call that gave you the error?

**Comment by khomicsk** [comment]
Dear Edward, thanks for getting back to me quickly. 

I actually found the problem which was that the q value of enhanced clustering was different (lower) from the q value of the initial (spatialCluster) clustering. After correction it worked. 

Regards

K
