### ISSUE TITLE
Error in H5Fopen(file) : HDF5. File accessibilty. Unable to open file.

### ISSUE THREAD

**Issue by zqsha** [edward130603/BayesSpace#61]
Hi there. Thanks for developing such an amazing toolbox. I run the example successfully. But when I run my own sample, I met the following error:
"Error in H5Fopen(file) : HDF5. File accessibilty. Unable to open file." Any thoughts on fixing it? 
For other samples, they're finished, but just for one sample, it reported the above error, I do not know why.

Thanks,
Cain

**Comment by edward130603** [comment]
Thanks for giving our tool a try. Can you provide the full function call that gave the error? I suspect the mcmc chains were not saved or in the wrong location. If you save it in a temp location, your system will eventually delete the files.

**Comment by zqsha** [comment]
Yes, sure. thanks for your reply. I used the following command line, and then it gave the error. Any suggestions?
"sce_sub <- spatialCluster(sce_sub, q=7, d=15, platform='Visium', nrep=50000, gamma=3, save.chain=TRUE)"

Prior to this command line, I run 
sce_sub <- sce[,colData(sce)$sample_name == sampleid]
dec <- scran::modelGeneVar(sce_sub)
top <- scran::getTopHVGs(dec, n = 2000)
sce_sub <- scater::runPCA(sce_sub, subset_row=top)
sce_sub <- spatialPreprocess(sce_sub, platform="Visium", skip.PCA=TRUE)
But, there is no reported error.

**Comment by edward130603** [comment]
Ok. The error probably occured when trying to save the mcmc chains. You might not have write permission to the directory it is trying to save to. Two options to fix this:

1. If you don't need to save the chains, use `save.chain = FALSE`.
2. If you do need to save the chains, specify a path and filename for the chains using `chain.fname`. For example:

```r
sce_sub <- spatialCluster(sce_sub, q=7, d=15, platform='Visium', nrep=50000, gamma=3, save.chain=TRUE,
                          chain.fname = "/path/to/my/directory/sce_sub.h5")
```

Also, as an aside, you should be able to do all the preprocessing using `spatialPreprocess` directly, without using the scran/scater functions:

```r
sce_sub <- sce[,colData(sce)$sample_name == sampleid]
sce_sub <- spatialPreprocess(sce_sub, platform="Visium") #by default, skip.PCA=FALSE
sce_sub <- spatialCluster(sce_sub, q=7, save.chain=FALSE)
```

**Comment by zqsha** [comment]
Great idea, thanks. I successfully finished the same task by muting the "save.chain" function. So, if I use the following command line to do the preprocessing
sce_sub <- spatialPreprocess(sce_sub, platform="Visium", n.PCs=15, n.HVGs=2000)

It should be equivalent to the following command lines. Right?
dec <- scran::modelGeneVar(sce_sub)
top <- scran::getTopHVGs(dec, n = 2000)
sce_sub <- scater::runPCA(sce_sub, subset_row=top)

**Comment by edward130603** [comment]
Yes, it's essentially the same. `spatialPreprocess` uses exact PCA by default while `scater::runPCA` uses approximate PCA, but should get basically the same results.
