### ISSUE TITLE
Differences in sample orientation between Seurat and BayesSpace

### ISSUE THREAD

**Issue by mvhunter1** [edward130603/BayesSpace#62]
Hi BayesSpace team, 
Thank you so much for this amazing tool - I have applied it to several Visium samples and the results are very impressive. I just ran the enhanced gene expression on a new Visium sample we recently generated. For whatever reason there is a difference in how the sample is oriented when read into Seurat vs BayesSpace. The image on the left is apoea gene expression with Seurat, and the image on the right is the BayesSpace enhanced expression (the not enhanced expression looks is oriented the same way). 
![image](https://user-images.githubusercontent.com/57913498/141339804-b970c96a-b293-4c98-acd7-5b7d87843ce9.png)

I haven't noticed this issue with previous Visium samples that i've analyzed in both Seurat and BayesSpace. Any idea what may have caused it or how I can reorient the BayesSpace sample? Thank you!

**Comment by mvhunter1** [comment]
And just to give a bit more information: I see the same difference in orientation between Seurat and BayesSpace when I convert the Seurat object to SCE, as I do when I read in the Spaceranger output directly to BayesSpace with readVisium. I'm running BayesSpace v0.99.5 and Seurat v4.0.4.

**Comment by edward130603** [comment]
Hi Miranda, we've seen this before as well on some samples. I think the issue occurs depending on whether `row` and `col` or `imagerow` and `imagecol` are used to orient the image. Usually `row` and `imagerow` are positively correlated but sometimes it's not, and that results in these orientation flips. Here's some code that should get around the issue. Basically just need to multiply `row` and/or `col` by `-1` to flip.

```r
library(BayesSpace)
library(ggplot2)

sce = getRDS("2020_ji_squamous-cell-carcinoma", "P4_rep1")
clusterPlot(sce, sce$row)+guides(fill = "none")
```
![image](https://user-images.githubusercontent.com/4656221/141346586-591841a2-aa60-4ea0-8ddd-94f0047213fb.png)

```r
sce2 = sce
sce2$row = sce2$row * -1
sce2$col = sce2$col * -1
clusterPlot(sce2, sce2$row)+guides(fill = "none")
```
![image](https://user-images.githubusercontent.com/4656221/141346757-ae2bffe4-feff-433d-8900-e35cf4375a52.png)

```r
sce2.enhanced = spatialEnhance(sce2, q = 5, init.method = "mclust", nrep = 1000, burn.in = 100)
clusterPlot(sce2.enhanced, sce2.enhanced$row)+guides(fill = "none")
```

![image](https://user-images.githubusercontent.com/4656221/141347871-3a91e409-f76c-4d3e-90cd-495c3461bea8.png)

**Comment by mvhunter1** [comment]
Thanks so much for the quick reply! That fixed the issue.
