### ISSUE TITLE
error in qTune

### ISSUE THREAD

**Issue by cherrie-g** [edward130603/BayesSpace#63]
Hi
I'm doing BayesSpace on my own data. And I met an error in qTune. The command and error were as below:

> sce <- qTune(sce, qs=seq(10, 30), platform="ST", d=43)
Neighbors were identified for 0 out of 6492 spots.
Fitting model...
Error in cluster.FUN(Y = as.matrix(Y), df_j = df_j, nrep = nrep, n = n,  :
  Not compatible with requested type: [type=NULL; target=double].

My sce object was transformed from Seurat object using "as.SingleCellExperiment". The meta.data of Seurat object was like below:
                                               orig.ident      nCount    nFeature    cell                                   x        y      seurat_clusters   row    col
sample_ABC:1740_15960   sample_ABC       1479          645     sample_ABC:1740_15960 1740 15960                 4         1500   2250
sample_ABC:2010_15150   sample_ABC       2637         1031    sample_ABC:2010_15150 2010 15150                 6         1770   1440

So could you tell me what's wrong with my script?

**Comment by edward130603** [comment]
The first issue I notice is related to the neighborhood structure not being detected correctly. (see message about 0 neighbors identified). Is this Visium data (your platform specified is "ST")? I notice that you have more than 5000 spots (which is the max for a visium capture area, and I believe the older ST tech has fewer than that). 

BayesSpace expects 4 columns of locations: `row`, `col`, `imagerow`, and `imagecol` (array coordinates and pixel coordinates respectively). I see your data has `x` and `y` instead. Perhaps try renaming those two columns to `imagecol` and `imagerow`. 

The second error message ("not compatible with requested type") means one of the inputs is missing. It's hard to debug without seeing the data more. Does your `sce` object have the PCA dimensions stored in the right place?

**Comment by cherrie-g** [comment]
Actually, this isn't ST/Visium data. I just chose 'ST' for analysis.  

The sce structure is like:
> sce
class: SingleCellExperiment
dim: 17625 6492
metadata(1): BayesSpace.data
assays(3): counts logcounts scaledata
rownames(17625): 0610005C13Rik 0610009B22Rik ... mt-Nd5 mt-Nd6
rowData names(1): is.HVG
colnames(6492): sample_ABC:9690_14640
  sample_ABC:8850_14760 ... sample_ABC:10110_16230
  sample_ABC:10410_14940
colData names(13): orig.ident nCount_Spatial ... col ident
reducedDimNames(2): PCA UMAP
altExpNames(2): SCT Spatial

And when i run bayesspace on other slides using the same method, it can work. So I'm very curious.

**Comment by edward130603** [comment]
Interesting. I'm not super sure what the issue is, but a couple things to look at. The error occurred because the C++ function `cluster.FUN` is expecting a double/numeric input for a parameter, but instead received `NULL`. These are the inputs to the C++ function:

```cpp
arma::mat Y, List df_j, int nrep, int n, int d, double gamma, int q, arma::vec init, NumericVector mu0, arma::mat lambda0, double alpha, double beta
```

So of these, `Y`, `gamma`, `init`, `mu0`, `lambda0`, `alpha`, or `beta` may have an issue since they are `double` type. 

To debug, we need to look at each of these in turn. `gamma`, `alpha`, and `beta` have defaults that shouldn't error so I'm guessing those are fine. For the others:

```r
library(BayesSpace)
library(mclust)

d = 43
Y = reducedDim(sce, "PCA")
d = min(ncol(Y), d)
Y = Y[, seq_len(d)]
Y = as.matrix(Y)
print(Y) #make sure this looks right
dim(Y) #should be 6492 rows by 43 columns

mu0 = colMeans(Y)
print(mu0)
length(mu0) #should be 43

lambda0 <- diag(0.01, ncol(Y))
print(lambda0)
dim(lambda0) #should be 43 by 43

init = Mclust(Y, q=10, "EEE", verbose = F)$classification
print(init)
length(init) #should be 6492
table(init) #should have 10 categories 
```

If this isn't helpful, I can take a look at the data if you can share the sample data with me via email (zhaoe(at)uw(dot)edu). If there is sensitive info, feel free to exclude the raw/processed assays (counts, logcounts, etc.) or provide just a subset of the `sce`.

**Comment by cherrie-g** [comment]
Hi Edward,
I tried as you said, and met a error in mlust step.

>\> init = Mclust(Y, q=10, "EEE", verbose = F)$classification
Error in if (G[1] == 1) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In sort(as.integer(unique(G))) : NAs introduced by coercion

Can you figure what's wrong with the data?

Bests.

**Comment by edward130603** [comment]
Oops the parameter q=10 should be G=10.
