### ISSUE TITLE
Run the clustering analysis across samples

### ISSUE THREAD

**Issue by zqsha** [edward130603/BayesSpace#66]
Hi Edward,
Thanks again for developing such an amazing toolbox. Everything works fine now on our system. I was just wondering whether it is possible to run this clustering analysis across samples. For example, in Maynard's paper, they have 12 samples. If we perform clustering analysis for each sample, the correspondence of each cluster across samples is not good. So, I was wondering whether this toolbox can work with clustering analysis across 12 samples, so finally it could also have 7 clusters, but across all of the samples. I guess the number of spots is large if we combine all of the samples, so this toolbox might be difficult to work with it?
Thanks,
cain

**Comment by edward130603** [comment]
Hi Cain, thanks for the question. Please check out our [joint clustering vignette](https://edward130603.github.io/BayesSpace/articles/joint_clustering.html), where we jointly cluster 4 samples from the DLPFC dataset. I've used BayesSpace to jointly cluster over 20 samples in another project so this approach is scalable, though requiring longer runtime and higher memory with more samples. In practice, reducing the number of iterations helps to alleviate some of these issues if needed.

Another simpler approach would be to (first harmonize, then) use mclust or louvain jointly cluster all the samples. The non-spatial clustering partition can then be used to initialize BayesSpace, where we run BayesSpace on each sample separately. This approach should also allow you to have corresponding clusters across samples.

**Comment by zqsha** [comment]
OK. Great idea. Thanks a lot. In this example (https://edward130603.github.io/BayesSpace/articles/joint_clustering.html ), you used 10000 iterations. If I want to try 40 samples using BayesSpace, how many times the iterations are necessary? At least 10000 iterations or 5000 iterations? 
Thanks,
Cain

**Comment by edward130603** [comment]
As always more is better. I'd recommend 10,000 if possible, but 5,000 might be fine though there will be higher chance of convergence issues depending on how good the initialization is.

**Comment by zqsha** [comment]
OK. Great, thank for your tips. When I run the example, I found it first uses "harmony" toolbox to normalize the data, which is great. So, it just adds the "HARMONY" data in the "reducedDims", and this "HARMONY" is finally used for the clustering analysis. But, in the "assays" of sce data, it still only has "counts" and "logcounts", which does not normalize the batch. That means, after we get the clusters and want to calculate the cluster-specific marker genes, then we can not use "HARMONY" data to calculate. We only can use the "logcounts" data to calculate, however, the "logcounts" in the "assays" of sce data does not normalize the batch effect. Does this approach also generate the "logcounts" after normalizing the batch effect?
Thanks,
Cain

**Comment by edward130603** [comment]
Generally for differential expression analysis, you would want to use the not harmonized data. The harmonization is only used for visualization + clustering purposes. Then, in the DE model, you can account for batch effects on the non-harmonized data by either pseudobulking (http://bioconductor.org/books/3.14/OSCA.multisample/multi-sample-comparisons.html) or using a mixed effects model such as nebula, glmmTMB, or MAST.

**Comment by zqsha** [comment]
OK. Great, thanks a lot. That's a very great point. So, in the example, it first used "Harmony" toolbox to normalize the batch effect. Before normalizing the batch effect, do we need to first normalize the library size? Alternatively, normalizing the batch effect in this step has been considered to normalize the library size effect?
Thanks,
Cain

**Comment by edward130603** [comment]
I think this depends on whether your DE models counts directly. If so, you can use the raw counts directly. If not, I would follow the tutorial for the tool that you are using.

In our vignette, we do log-normalization (for lib size) and PCA first using `spatialPreprocess()` before using harmony for the batch correction.

**Comment by zqsha** [comment]
Hi Edward,
When I run the cross-sample clustering analysis two times using the same script and samples, I found the results might be different. How can I replicate the results?

![Picture1](https://user-images.githubusercontent.com/27337033/150554670-73a0d22a-33c7-49c5-a651-6b7493042188.png)

Thanks,
Cain

**Comment by edward130603** [comment]
I think this is most likely an initialization issue. The simplest "solution" is to just set a seed before running your script and it will be consistent. If you want to try to solve the problem of initialization, I think two approaches:

1. Use a more robust initialization. BayesSpace uses mclust to initialize by default. The teigen package may provide a more robust clustering than mclust, since teigen tests many initializations and looks for convergence between them. We don't do this by default since teigen sometimes doesn't converge. But when it does, it typically provides better initialization for BayesSpace.
```r
library(teigen)
teigen.init = teigen(reducedDim(sce, "HARMONY), Gs = 3, models = "CCCC")
```
Then use `teigen.init` in the `init` parameter of `spatialCluster()`.

2. Take the results from the different clustering partitions and use some consensus clustering approach. Not sure if there's any R package written already that does this for you.

But again, if you just need to ensure you can replicate results on each run, setting a random seed at the start of your script should be enough.
