### ISSUE TITLE
how to speed up spatialEnhance

### ISSUE THREAD

**Issue by lengfei5** [edward130603/BayesSpace#70]
Hi there, 

Thanks for the nice algorithm and R package.
I have a visium data with 12000 genes * 1000 spots. 
When I run spatialEnhance, it takes > 1h and does not finish.
Is it normal in my case ? is there way to speed up by using multiple rams ? 
Thanks. 

Best,
Jingkui

**Comment by lengfei5** [comment]
PS: I running the Rstuido in cluster with ~ 100G memory and 32 cores

**Comment by edward130603** [comment]
The enhancement algorithm is quite computationally intensive, and we are not able to parallelize the procedure. I expect it to finish within a few hours.

**Comment by lengfei5** [comment]
I see and thank you for the prompt and informative answer. 
So it is normal to have such long running time. 
Thanks.
