### ISSUE TITLE
IDC/OC IF image data

### ISSUE THREAD

**Issue by jbreynier** [edward130603/BayesSpace#78]
Thank you very much for providing this tool. Could you please share the data related to the cell segmentation and IF intensity analysis for both the ductal and the ovarian cancer samples (supp. figure 7 and 8)? It would be very useful to have for each spot: whether the tissue is in focus, the cell count, and the fluorescent marker data.

Thank you very much in advance!

**Comment by edward130603** [comment]
Thanks for your interest in our work. I'll track down the data and share with you in a couple of days.

**Comment by edward130603** [comment]
Sorry for the delay. I've attached most of the relevant annotations. For the *.intensity.RDS files, the order of the data is the same as the SingleCellExperiment from `getRDS("2020_10X-demo_ovarian-cancer", "whole_transcriptome")` and `getRDS("2020_10X-IDC", "IDC1")`. The cell counts file is in the format where spot.idx is the index of the spot in the SCE. All spots not in this file are out of focus and therefore do not have cell segmentation results. 

Hope this helps!
[annotations.zip](https://github.com/edward130603/BayesSpace/files/8598410/annotations.zip)

**Comment by jbreynier** [comment]
Thank you very much for your help! This is perfect.
