### ISSUE TITLE
BayesSpace on high-res spatial omics data

### ISSUE THREAD

**Issue by jleechung** [edward130603/BayesSpace#85]
Hi @edward130603 ,

Can BayesSpace be used for clustering high-resolution spatial omics data (e.g. MERFISH)?

**Comment by jleechung** [comment]
Thanks for the clarification and pointers. Would something like taking the k-nearest spatial neighbors work? i.e.:

```r
sce <- exampleSCE() 
k <- 10 # hyperparam

positions = cbind(sce$row, sce$col)
knn <- dbscan::kNN(positions, k = k)$id - 1
df_j <- split(knn, seq(nrow(knn)))
names(df_j) <- NULL
```

I guess this would also be generalizable to Visium (k=6) and ST (k=4).

**Comment by edward130603** [comment]
Yes, k nearest neighbors should work as well!

**Comment by jleechung** [comment]
Cool, thanks!
